### ISSUE TITLE
Dedi-Server

### ISSUE THREAD

**Issue by jason0611** [HelferB/FS19_LicensePlates#4] opened 2021-02-14 17:08 UTC
Hi, 

am I right here for issues with new mod FS19_LicensPlates in Giant's ModHub? 
If I'm right: Thank you very much for your nice approach to bring a note of personalization to the vehicles in FS19.
It works very fine in SinglePlayer, but unfortunately there is a problem using your mod in MultiPlayer on a Dedi-Server. 
I've attached two pairs of log files: One on my standard game MVP19 on Dediserver with all mods active (server+client), and one on a Testgame on Felsbrunn with only your mod active.

In standard game, the synchronization while joining the game won't finish, while LUA-Errors are shown on server an client. The Lua errors on server are related to your mod, the errors on client are related to mismatch in network-communication.

In the testgame joining is possible, but the LUA-Errors on the servers are the same.

[serverlog_MVP19.txt](https://github.com/HelferB/FS19_LicensePlates/files/5978101/serverlog_MVP19.txt)
[clientlog_MVP19.txt](https://github.com/HelferB/FS19_LicensePlates/files/5978102/clientlog_MVP19.txt)

[serverlog_felsbrunn.txt](https://github.com/HelferB/FS19_LicensePlates/files/5978103/serverlog_felsbrunn.txt)
[clientlog_felsbrunn.txt](https://github.com/HelferB/FS19_LicensePlates/files/5978105/clientlog_felsbrunn.txt)

It would be very nice if the errors could be fixed so that your mod works on Dediservers, too. If support is needed to test on a Dediserver, just talk to me.

As I'm a native German Speaker, we may switch over to German if you like.

Regards,
Martin

**Comment by HelferB** [comment] 2021-02-15 17:20
The problem is not related to the dedicated server, it seems that this also occurs on multiplayer sessions. This is the important part:

```
Error: Running LUA method 'packetReceived'.
LicensePlates.lua:219: attempt to index local 'self' (a nil value)
Error: Running LUA method 'packetReceived'.
LicensePlates.lua:240: attempt to index local 'self' (a nil value)
Error: Running LUA method 'packetReceived'.
LicensePlates.lua:261: attempt to index local 'self' (a nil value)
```

This is likely caused by mod vehicles with a custom vehicle type, which are added after the license plates specialization is initiated, I am working on an update, which will be released after the two weeks update lock.

**Closed as completed** 2021-03-01 16:53 UTC
Labels: bug, good first issue
